# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'allenleenet'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-56089889-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}
- {name: 'Treatment History', path: 'menu', url: 'treatments.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/leea'}
- {icon: 'twitter', link: 'https://twitter.com/allen_lee_'}
- {icon: 'facebook', link: 'https://www.facebook.com/allen.lee.812'}
#- {icon: 'linkedin', link: 'http://www.linkedin.com/in//'}
- {icon: 'envelope', link: 'mailto:al@allenlee.net'}
- {icon: 'rss-square', link: '/atom.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Share on social media'

#related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
